 ----DROP CONSTRAINTS FK OF ASSET CATEGORY 
ALTER TABLE ASSET_PROFILES
DROP CONSTRAINT SYS_C0011473;

-----ALTER CONSTRAINTS ASSET CATEGORY FK TO LIBRARY TYPES TABLE
ALTER TABLE "FAIS"."ASSET_PROFILES" ADD CONSTRAINT "SYS_C0011473" FOREIGN KEY ("ASSET_CATEGORY_SEQ")
	REFERENCES "FAIS"."LIBRARY_TYPES" ("LIB_TYPE_SEQ") ENABLE;
Insert into FAIS.ASSET_PROFILES (ASSET_SEQ,ASSET_NAME,ASSET_CATEGORY_SEQ,ASSET_CLASS_SEQ,DESCRIPTION,RCA_GL_SEQ,SL_NO_SEQ,COST_CENTER,ECONOMIC_LIFE,RESIDUAL_LIFE,IS_ACTIVE,STATUS_DATE,DATE_CREATED,DATE_MODIFIED,USER_CREATED,USER_MODIFIED) values (11,'Test',12,1,'est',178,178,50,'eco test','50','N',to_date('20-NOV-23','DD-MON-RR'),to_date('20-NOV-23','DD-MON-RR'),to_date('07-MAR-24','DD-MON-RR'),1,null);
Insert into FAIS.ASSET_PROFILES (ASSET_SEQ,ASSET_NAME,ASSET_CATEGORY_SEQ,ASSET_CLASS_SEQ,DESCRIPTION,RCA_GL_SEQ,SL_NO_SEQ,COST_CENTER,ECONOMIC_LIFE,RESIDUAL_LIFE,IS_ACTIVE,STATUS_DATE,DATE_CREATED,DATE_MODIFIED,USER_CREATED,USER_MODIFIED) values (12,'testing',12,null,'haha',178,178,50,'life test','50','Y',to_date('20-NOV-23','DD-MON-RR'),to_date('20-NOV-23','DD-MON-RR'),to_date('07-MAR-24','DD-MON-RR'),1,null);
Insert into FAIS.ASSET_PROFILES (ASSET_SEQ,ASSET_NAME,ASSET_CATEGORY_SEQ,ASSET_CLASS_SEQ,DESCRIPTION,RCA_GL_SEQ,SL_NO_SEQ,COST_CENTER,ECONOMIC_LIFE,RESIDUAL_LIFE,IS_ACTIVE,STATUS_DATE,DATE_CREATED,DATE_MODIFIED,USER_CREATED,USER_MODIFIED) values (6,'Asset Test',12,null,'description test',178,179,40,'econ test','40','Y',to_date('20-NOV-23','DD-MON-RR'),to_date('20-NOV-23','DD-MON-RR'),to_date('07-MAR-24','DD-MON-RR'),1,null);

------ ROLE PERMISSION (SHOW ICON OF ASSET PROFILE) 
Insert into FAIS.ROLE_PERMISSIONS (ROLE_PER_SEQ,ROLE_SEQ,MODULE_SEQ,P_CREATE,P_READ,P_UPDATE,DATE_CREATED,DATE_MODIFIED,DATE_REMOVED,USER_CREATED,USER_MODIFIED) values (32,1,14,'Y','Y','Y',to_date('23-NOV-23','DD-MON-RR'),to_date('23-NOV-23','DD-MON-RR'),null,1,1);


----- UPDATE ICON 
UPDATE modules 
SET icon = 'real_estate_agent'
WHERE module_seq = 14;


----INSERT DATA ON LIBRARY_TYPES 
Insert into FAIS.LIBRARY_TYPES (LIB_TYPE_SEQ,LIB_TYPE_NAME,LIB_TYPE_CODE,LIB_TYPE_DESC,IS_ACTIVE,STATUS_DATE,DATE_CREATED,DATE_MODIFIED,USER_CREATED,USER_MODIFIED) values (12,'Major Equipment','AST','Major Equipment','Y',to_date('20-NOV-23','DD-MON-RR'),to_date('20-NOV-23','DD-MON-RR'),to_date('06-FEB-24','DD-MON-RR'),1,null);
