--------------------------------------------------------
--  DDL for Table PROJECT_PROFILE
--------------------------------------------------------

  CREATE TABLE "FAIS"."PROJECT_PROFILE" 
   (	"PROJECT_SEQ" NUMBER(*,0), 
	"PROJECT_NAME" VARCHAR2(100 BYTE), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"PROJ_CLASS_SEQ" NUMBER(*,0), 
	"TPSR_MONTH" DATE, 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"STATUS_DATE" DATE DEFAULT systimestamp, 
	"DATE_CREATED" DATE DEFAULT systimestamp, 
	"DATE_MODIFIED" DATE DEFAULT systimestamp, 
	"USER_CREATED" NUMBER(*,0), 
	"USER_MODIFIED" NUMBER(*,0) DEFAULT NULL, 
	"UDF1" VARCHAR2(250 BYTE), 
	"UDF2" VARCHAR2(250 BYTE), 
	"UDF3" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007250
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."SYS_C007250" ON "FAIS"."PROJECT_PROFILE" ("PROJECT_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007253
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."SYS_C007253" ON "FAIS"."PROJECT_PROFILE" ("PROJECT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger PROJECT_PROF_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROJECT_PROF_MODIFIED" 
BEFORE UPDATE ON project_profile
FOR EACH ROW
BEGIN
    SELECT systimestamp into :new.date_modified FROM DUAL;
END;

/
ALTER TRIGGER "FAIS"."PROJECT_PROF_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJECT_PROF_AUTO_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROJECT_PROF_AUTO_INCREMENT" 
BEFORE INSERT ON project_profile
FOR EACH ROW
BEGIN
  SELECT project_seq_seq.NEXTVAL INTO :NEW.project_seq FROM DUAL;
END;
/
ALTER TRIGGER "FAIS"."PROJECT_PROF_AUTO_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJECT_PROFILE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROJECT_PROFILE_TRG" 
BEFORE INSERT ON PROJECT_PROFILE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PROJECT_SEQ IS NULL THEN
      SELECT PROJECT_PROFILE_SEQ1.NEXTVAL INTO :NEW.PROJECT_SEQ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."PROJECT_PROFILE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECT_PROFILE
--------------------------------------------------------

  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("PROJECT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("PROJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("PROJ_CLASS_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("TPSR_MONTH" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("STATUS_DATE" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("USER_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD PRIMARY KEY ("PROJECT_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD CONSTRAINT "SYS_C007253" UNIQUE ("PROJECT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_PROFILE
--------------------------------------------------------

  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD CONSTRAINT "SYS_C007254" FOREIGN KEY ("USER_CREATED")
	  REFERENCES "FAIS"."USERS" ("USER_SEQ") ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD CONSTRAINT "SYS_C007255" FOREIGN KEY ("USER_MODIFIED")
	  REFERENCES "FAIS"."USERS" ("USER_SEQ") ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD FOREIGN KEY ("PROJ_CLASS_SEQ")
	  REFERENCES "FAIS"."LIBRARY_TYPE_OPTIONS" ("LIB_TYPE_OPT_SEQ") ENABLE;


	  --------------------------------------------------------
--  DDL for Table PROJECT_PROFILE_COMPONENTS
--------------------------------------------------------

  CREATE TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" 
   (	"PROFILE_COMP_SEQ" NUMBER(*,0), 
	"PROFILE_SEQ" NUMBER(*,0), 
	"PROJECT_COMP_DETAILS" VARCHAR2(250 BYTE), 
	"PROJECT_STAGE_SEQ" NUMBER(*,0), 
	"TRANS_GRID_SEQ" NUMBER(*,0), 
	"START_DATE" DATE, 
	"TARGET_DATE" DATE, 
	"COMPLETION_DATE" DATE, 
	"INSPECTION_DATE" DATE, 
	"INITIAL_AMR_MONTH" DATE, 
	"DATE_CREATED" DATE DEFAULT systimestamp, 
	"DATE_MODIFIED" DATE DEFAULT systimestamp, 
	"DATE_REMOVED" DATE, 
	"USER_CREATED" NUMBER(*,0), 
	"USER_MODIFIED" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROJECT_PROFILE_COMPONENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."PROJECT_PROFILE_COMPONENTS_PK" ON "FAIS"."PROJECT_PROFILE_COMPONENTS" ("PROFILE_COMP_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger METERING_PROFILES_COMPONENTS_
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."METERING_PROFILES_COMPONENTS_" 
BEFORE INSERT ON PROJECT_PROFILE_COMPONENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."METERING_PROFILES_COMPONENTS_" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJECT_PROFILE_COMPONENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROJECT_PROFILE_COMPONENTS_TRG" 
BEFORE INSERT ON PROJECT_PROFILE_COMPONENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."PROJECT_PROFILE_COMPONENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJECT_PROFILE_COMPONENTS_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROJECT_PROFILE_COMPONENTS_TR" 
BEFORE INSERT ON PROJECT_PROFILE_COMPONENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PROFILE_COMP_SEQ IS NULL THEN
      SELECT PROJECT_PROFILE_COMPONENTS_SE1.NEXTVAL INTO :NEW.PROFILE_COMP_SEQ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."PROJECT_PROFILE_COMPONENTS_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECT_PROFILE_COMPONENTS
--------------------------------------------------------

  ALTER TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" MODIFY ("USER_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" MODIFY ("PROFILE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" MODIFY ("PROFILE_COMP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" ADD CONSTRAINT "PROJECT_PROFILE_COMPONENTS_PK" PRIMARY KEY ("PROFILE_COMP_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_PROFILE_COMPONENTS
--------------------------------------------------------

  ALTER TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" ADD CONSTRAINT "PROJECT_PROFILE_COMPONENT_FK1" FOREIGN KEY ("PROFILE_SEQ")
	  REFERENCES "FAIS"."PROJECT_PROFILE" ("PROJECT_SEQ") ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" ADD CONSTRAINT "PROJECT_PROFILE_COMPONENT_FK2" FOREIGN KEY ("USER_CREATED")
	  REFERENCES "FAIS"."USERS" ("USER_SEQ") ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE_COMPONENTS" ADD CONSTRAINT "PROJECT_PROFILE_COMPONENT_FK3" FOREIGN KEY ("USER_MODIFIED")
	  REFERENCES "FAIS"."USERS" ("USER_SEQ") ENABLE;
