--------------------------------------------------------
--  DDL for Table PROJECT_PROFILE
--------------------------------------------------------

  CREATE TABLE "FAIS"."PROJECT_PROFILE" 
   (	"PROJECT_SEQ" NUMBER(*,0), 
	"PROJECT_NAME" VARCHAR2(100 BYTE), 
	"PROJECT_STAGE_SEQ" NUMBER(*,0), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"PROJ_CLASS_SEQ" NUMBER(*,0), 
	"TPSR_MONTH" DATE, 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"STATUS_DATE" DATE DEFAULT systimestamp, 
	"DATE_CREATED" DATE DEFAULT systimestamp, 
	"DATE_MODIFIED" DATE DEFAULT systimestamp, 
	"USER_CREATED" NUMBER(*,0), 
	"USER_MODIFIED" NUMBER(*,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007250
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."SYS_C007250" ON "FAIS"."PROJECT_PROFILE" ("PROJECT_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007253
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."SYS_C007253" ON "FAIS"."PROJECT_PROFILE" ("PROJECT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger PROJECT_PROF_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROJECT_PROF_MODIFIED" 
BEFORE UPDATE ON project_profile
FOR EACH ROW
BEGIN
    SELECT systimestamp into :new.date_modified FROM DUAL;
END;




/
ALTER TRIGGER "FAIS"."PROJECT_PROF_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJECT_PROF_AUTO_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROJECT_PROF_AUTO_INCREMENT" 
BEFORE INSERT ON project_profile
FOR EACH ROW
BEGIN
  SELECT project_seq_seq.NEXTVAL INTO :NEW.project_seq FROM DUAL;
END;




/
ALTER TRIGGER "FAIS"."PROJECT_PROF_AUTO_INCREMENT" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECT_PROFILE
--------------------------------------------------------

  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD CONSTRAINT "SYS_C007253" UNIQUE ("PROJECT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD PRIMARY KEY ("PROJECT_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("USER_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("STATUS_DATE" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("TPSR_MONTH" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("PROJ_CLASS_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("PROJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROJECT_PROFILE" MODIFY ("PROJECT_SEQ" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_PROFILE
--------------------------------------------------------

  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD FOREIGN KEY ("PROJECT_STAGE_SEQ")
	  REFERENCES "FAIS"."LIBRARY_TYPE_OPTIONS" ("LIB_TYPE_OPT_SEQ") ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD FOREIGN KEY ("PROJ_CLASS_SEQ")
	  REFERENCES "FAIS"."LIBRARY_TYPE_OPTIONS" ("LIB_TYPE_OPT_SEQ") ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD CONSTRAINT "SYS_C007254" FOREIGN KEY ("USER_CREATED")
	  REFERENCES "FAIS"."USERS" ("USER_SEQ") ENABLE;
  ALTER TABLE "FAIS"."PROJECT_PROFILE" ADD CONSTRAINT "SYS_C007255" FOREIGN KEY ("USER_MODIFIED")
	  REFERENCES "FAIS"."USERS" ("USER_SEQ") ENABLE;

--------------------------------------------------------
--  Create Sequence for Table PROJECT_PROFILE
--------------------------------------------------------

CREATE SEQUENCE  "FAIS"."PROJECT_SEQ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;