----ADD UDF COLUMNS IN ASSET_PROFILE
ALTER TABLE ASSET_PROFILES
ADD UDF1 VARCHAR2(250) NULL

ALTER TABLE ASSET_PROFILES
ADD UDF2 VARCHAR2(250) NULL

ALTER TABLE ASSET_PROFILES
ADD UDF3 VARCHAR2(250) NULL