----ADD UDF COLUMNS IN METERING_PROFILES
ALTER TABLE METERING_PROFILES
ADD UDF1 VARCHAR2(250) NULL

ALTER TABLE METERING_PROFILES
ADD UDF2 VARCHAR2(250) NULL

ALTER TABLE METERING_PROFILES
ADD UDF3 VARCHAR2(250) NULL

ALTER TABLE METERING_PROFILES
ADD METERING_CLASS_SEQ NUMBER NULL

ALTER TABLE METERING_PROFILES
ADD LINE_SEGMENT VARCHAR2(100) NULL