--------------------------------------------------------
--  File created 
--------------------------------------------------------
DROP TABLE "FAIS"."TRANS_LINE_PROFILES" cascade constraints;

--------------------------------------------------------
--  DDL for Table TRANS_LINE_PROFILES
--------------------------------------------------------

  CREATE TABLE "FAIS"."TRANS_LINE_PROFILES" 
   (	"TRANS_LINE_SEQ" NUMBER(*,0), 
	"LINE_STRETCH" NUMBER(*,0), 
	"VOLTAGE_SEQ" NUMBER(*,0), 
	"ST" NUMBER(*,0) DEFAULT 0, 
	"SP" NUMBER(*,0) DEFAULT 0, 
	"CP" NUMBER(*,0) DEFAULT 0, 
	"WP" NUMBER(*,0) DEFAULT 0, 
	"SLWT" NUMBER(*,0) DEFAULT 0, 
	"INSTALLATION_DATE" DATE, 
	"ROUTE_LENGTH" NUMBER, 
	"NO_CIRCUIT_SEQ" NUMBER(*,0), 
	"CIRCUIT_LENGTH" NUMBER(*,0), 
	"NO_CONDUCTOR" NUMBER(*,0), 
	"REMARKS" VARCHAR2(250 BYTE), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"STATUS_DATE" DATE DEFAULT systimestamp, 
	"DATE_CREATED" DATE DEFAULT systimestamp, 
	"DATE_MODIFIED" DATE DEFAULT systimestamp, 
	"USER_CREATED" NUMBER(*,0), 
	"USER_MODIFIED" NUMBER(*,0) DEFAULT NULL, 
	"UDF1" VARCHAR2(250 BYTE), 
	"UDF2" VARCHAR2(250 BYTE), 
	"UDF3" VARCHAR2(250 BYTE), 
	"CONDUCTOR_SIZE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FAIS.TRANS_LINE_PROFILES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007039
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."SYS_C007039" ON "FAIS"."TRANS_LINE_PROFILES" ("TRANS_LINE_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRANS_LINE_MODIFIED
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."TRANS_LINE_MODIFIED" 
BEFORE UPDATE ON trans_line_profiles
FOR EACH ROW
BEGIN
    SELECT systimestamp into :new.date_modified FROM DUAL;
END;





/
ALTER TRIGGER "FAIS"."TRANS_LINE_MODIFIED" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANS_LINE_PROFILES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."TRANS_LINE_PROFILES_TRG" 
BEFORE INSERT ON TRANS_LINE_PROFILES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
    BEGIN
    IF INSERTING AND :NEW.TRANS_LINE_SEQ IS NULL THEN
      SELECT trans_line_profiles_seq.NEXTVAL INTO :NEW.TRANS_LINE_SEQ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."TRANS_LINE_PROFILES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
--------------------------------------------------------
--  Constraints for Table TRANS_LINE_PROFILES
--------------------------------------------------------

  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("REMARKS" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("TRANS_LINE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("LINE_STRETCH" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("VOLTAGE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("ST" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("SP" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("CP" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("WP" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("STATUS_DATE" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" MODIFY ("USER_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" ADD PRIMARY KEY ("TRANS_LINE_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANS_LINE_PROFILES
--------------------------------------------------------

  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" ADD FOREIGN KEY ("VOLTAGE_SEQ")
	  REFERENCES "FAIS"."LIBRARY_TYPE_OPTIONS" ("LIB_TYPE_OPT_SEQ") ENABLE;
  ALTER TABLE "FAIS"."TRANS_LINE_PROFILES" ADD FOREIGN KEY ("CIRCUIT_LENGTH")
	  REFERENCES "FAIS"."LIBRARY_TYPE_OPTIONS" ("LIB_TYPE_OPT_SEQ") ENABLE;
