<--INSERT USAGE PERMISSION ADD/EDIT for Administrator SCRIPT-> 
INSERT INTO FAIS.ROLE_PERMISSIONS (ROLE_SEQ, MODULE_SEQ, P_CREATE, P_READ, P_UPDATE, DATE_CREATED, DATE_MODIFIED, DATE_REMOVED, USER_CREATED, USER_MODIFIED) 
VALUES (1, 23, 'Y', 'Y', 'Y', TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), 1, null);

<--INSERT SIDEBAR PERMISSION FOR ADMINISTRATOR METERING PROFILE SCRIPT-> 
INSERT INTO FAIS.ROLE_PERMISSIONS (ROLE_SEQ, MODULE_SEQ, P_CREATE, P_READ, P_UPDATE, DATE_CREATED, DATE_MODIFIED, DATE_REMOVED, USER_CREATED, USER_MODIFIED) 
VALUES (1, 15, 'Y', 'Y', 'Y', TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), 1, null);

<--CREATE NEW ROLE METERING LIBRARIAN--> 
Insert into FAIS.ROLES (ROLE_SEQ,ROLE_NAME,ROLE_DESCRIPTION,IS_ACTIVE,STATUS_DATE,DATE_CREATED,DATE_MODIFIED,USER_CREATED,USER_MODIFIED) values (13,'Metering Librarian','Metering Librarian','Y',to_date('01-JAN-01','DD-MON-RR'),to_date('01-JAN-01','DD-MON-RR'),to_date('29-APR-24','DD-MON-RR'),1,null);

<---INSERT SIDEBAR PERMISSION FOR METERING LIBRARIAN SCRIPT--> 
INSERT INTO FAIS.ROLE_PERMISSIONS (ROLE_SEQ, MODULE_SEQ, P_CREATE, P_READ, P_UPDATE, DATE_CREATED, DATE_MODIFIED, DATE_REMOVED, USER_CREATED, USER_MODIFIED) 
VALUES (13, 15, 'Y', 'Y', 'Y', TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), 1, null);


<---INSERT USAGE PERMISSION ADD/EDIT FOR METERING LIBRARIAN-->
INSERT INTO FAIS.ROLE_PERMISSIONS (ROLE_SEQ, MODULE_SEQ, P_CREATE, P_READ, P_UPDATE, DATE_CREATED, DATE_MODIFIED, DATE_REMOVED, USER_CREATED, USER_MODIFIED) 
VALUES (13, 23, 'Y', 'Y', 'Y', TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), 1, null);

