
<------CREATE ARMD ANALYST ROLE AND INSERT ON ROLE TABLE ----> 
Insert into FAIS.ROLES (ROLE_SEQ,ROLE_NAME,ROLE_DESCRIPTION,IS_ACTIVE,STATUS_DATE,DATE_CREATED,DATE_MODIFIED,USER_CREATED,USER_MODIFIED) values (14,'ARMD Analyst','ARMD Analyst','Y',to_date('06-MAY-24','DD-MON-RR'),to_date('06-MAY-24','DD-MON-RR'),to_date('06-MAY-24','DD-MON-RR'),1,null);

<---INSERT USAGE PERMISSION ADD/EDIT TRANSMISSION LINE PROFILE ON MODULE TABLE-->
Insert into FAIS.MODULES (MODULE_SEQ,MODULE_NAME,MODULE_DESCRIPTION,URL,IS_ACTIVE,STATUS_DATE,DATE_CREATED,DATE_MODIFIED,USER_CREATED,USER_MODIFIED,SEQUENCE,GROUP_NAME,ICON) values (24,'Add/Edit Transmission Profile','add / edit transmission','/','Y',to_date('06-MAY-24','DD-MON-RR'),to_date('06-MAY-24','DD-MON-RR'),to_date('06-MAY-24','DD-MON-RR'),1,null,null,'N/A',null);

<--INSERT SIDEBAR PERMISSION FOR ADMINISTRATOR METERING PROFILE SCRIPT-> 
INSERT INTO FAIS.ROLE_PERMISSIONS (ROLE_SEQ, MODULE_SEQ, P_CREATE, P_READ, P_UPDATE, DATE_CREATED, DATE_MODIFIED, DATE_REMOVED, USER_CREATED, USER_MODIFIED) 
VALUES (1, 16, 'Y', 'Y', 'Y', TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), 1, null);


<--INSERT SIDEBAR PERMISSION FOR ARMD ANALYST METERING PROFILE SCRIPT-> 
INSERT INTO FAIS.ROLE_PERMISSIONS (ROLE_SEQ, MODULE_SEQ, P_CREATE, P_READ, P_UPDATE, DATE_CREATED, DATE_MODIFIED, DATE_REMOVED, USER_CREATED, USER_MODIFIED) 
VALUES (14, 16, 'Y', 'Y', 'Y', TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), 1, null);


<---INSERT USAGE PERMISSION ADD/EDIT for ADMINISTRATOR ---> 
INSERT INTO FAIS.ROLE_PERMISSIONS (ROLE_SEQ, MODULE_SEQ, P_CREATE, P_READ, P_UPDATE, DATE_CREATED, DATE_MODIFIED, DATE_REMOVED, USER_CREATED, USER_MODIFIED) 
VALUES (1, 23, 'Y', 'Y', 'Y', TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), 1, null);


<--INSERT SIDEBAR PERMISSION FOR ARMD ANALYST METERING PROFILE SCRIPT-> 
INSERT INTO FAIS.ROLE_PERMISSIONS (ROLE_SEQ, MODULE_SEQ, P_CREATE, P_READ, P_UPDATE, DATE_CREATED, DATE_MODIFIED, DATE_REMOVED, USER_CREATED, USER_MODIFIED) 
VALUES (14, 23, 'Y', 'Y', 'Y', TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), TO_DATE('23-NOV-23', 'DD-MON-RR'), 1, null);
