----ADD RANKING COLUMN IN LIBRARY TYPE OPTIONS TABLE
ALTER TABLE LIBRARY_TYPE_OPTIONS
ADD RANKING NUMBER NULL

ALTER TABLE LIBRARY_TYPE_OPTIONS
ADD UDF1 VARCHAR2(250) NULL

ALTER TABLE LIBRARY_TYPE_OPTIONS
ADD UDF2 VARCHAR2(250) NULL

ALTER TABLE LIBRARY_TYPE_OPTIONS
ADD UDF3 VARCHAR2(250) NULL