-- UPDATE PLANT_INFORMATION_DETAILS
ALTER TABLE PLANT_INFORMATION_DETAILS
ADD COST_CENTER_TYPE_LTO NUMBER(38,0) NULL;

-- UPDATE PLANT_INFORMATION
ALTER TABLE PLANT_INFORMATION
ADD UDF1 VARCHAR2(250) NULL;

ALTER TABLE PLANT_INFORMATION
ADD UDF2 VARCHAR2(250) NULL;

ALTER TABLE PLANT_INFORMATION
ADD UDF3 VARCHAR2(250) NULL;

ALTER TABLE PLANT_INFORMATION
ADD COMM_DATE DATE NULL;