--------------------------------------------------------
--  File created - Friday-February-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COST_CENTER
--------------------------------------------------------

  CREATE TABLE "FAIS"."COST_CENTER" 
   (    "COST_CENTER_SEQ" NUMBER(38,0), 
    "FG_CODE" NVARCHAR2(5), 
    "COST_CENTER_NUMBER" NUMBER, 
    "COST_CENTER_NAME" VARCHAR2(50 BYTE), 
    "SHORT_NAME" VARCHAR2(20 BYTE), 
    "USER_CREATED" NUMBER(38,0), 
    "DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FAIS.COST_CENTER
SET DEFINE OFF;
Insert into FAIS.COST_CENTER (COST_CENTER_SEQ,FG_CODE,COST_CENTER_NUMBER,COST_CENTER_NAME,SHORT_NAME,USER_CREATED,DATE_CREATED) values (1,'T5',5900486,'OCH, CEBU-NEGROS-PANAY INTERCONNECTION PROJECT','OCH',1,to_date('01/31/2024','MM/DD/RRRR'));
Insert into FAIS.COST_CENTER (COST_CENTER_SEQ,FG_CODE,COST_CENTER_NUMBER,COST_CENTER_NAME,SHORT_NAME,USER_CREATED,DATE_CREATED) values (2,'T1',5900487,'OCH2, CEBU-NEGROS-PANAY INTERCONNECTION PROJECT','OCH2',1,to_date('01/31/2024','MM/DD/RRRR'));
--------------------------------------------------------
--  DDL for Index COST_CENTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."COST_CENTER_PK" ON "FAIS"."COST_CENTER" ("COST_CENTER_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger COST_CENTER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."COST_CENTER_TRG" 
BEFORE INSERT ON COST_CENTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COST_CENTER_SEQ IS NULL THEN
      SELECT COST_CENTER_SEQ.NEXTVAL INTO :NEW.COST_CENTER_SEQ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."COST_CENTER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table COST_CENTER
--------------------------------------------------------

  ALTER TABLE "FAIS"."COST_CENTER" ADD CONSTRAINT "COST_CENTER_PK" PRIMARY KEY ("COST_CENTER_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAIS"."COST_CENTER" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."COST_CENTER" MODIFY ("USER_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."COST_CENTER" MODIFY ("SHORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."COST_CENTER" MODIFY ("COST_CENTER_NAME" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."COST_CENTER" MODIFY ("COST_CENTER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."COST_CENTER" MODIFY ("FG_CODE" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."COST_CENTER" MODIFY ("COST_CENTER_SEQ" NOT NULL ENABLE);