
  CREATE TABLE "FAIS"."COST_CENTER" 
   (	"COST_CENTER_SEQ" NUMBER(38,0) NOT NULL ENABLE, 
	"FG_CODE" NVARCHAR2(5) NOT NULL ENABLE, 
	"COST_CENTER_NUMBER" NUMBER NOT NULL ENABLE, 
	"COST_CENTER_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SHORT_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USER_CREATED" NUMBER(38,0) NOT NULL ENABLE, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	 CONSTRAINT "COST_CENTER_PK" PRIMARY KEY ("COST_CENTER_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE TRIGGER "FAIS"."COST_CENTER_TRG" 
BEFORE INSERT ON COST_CENTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COST_CENTER_SEQ IS NULL THEN
      SELECT COST_CENTER_SEQ.NEXTVAL INTO :NEW.COST_CENTER_SEQ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."COST_CENTER_TRG" ENABLE;

