--------------------------------------------------------
--  DDL for Table PROFORMA_ENTRIES_HEADER
--------------------------------------------------------

  CREATE TABLE "FAIS"."PROFORMA_ENTRIES_HEADER" 
   (	"PROFORMA_ENTRY_SEQ" NUMBER(38,0), 
	"TRAN_TYPE_SEQ" NUMBER(38,0), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"STATUS_DATE" DATE, 
	"DATE_CREATED" DATE, 
	"DATE_MODIFIED" DATE, 
	"USER_CREATED" NUMBER(38,0), 
	"USER_MODIFIED" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFORMA_ENTRIES_HEADER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."PROFORMA_ENTRIES_HEADER_PK" ON "FAIS"."PROFORMA_ENTRIES_HEADER" ("PROFORMA_ENTRY_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger PROFORMA_ENTRIES_HEADER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROFORMA_ENTRIES_HEADER_TRG" 
BEFORE INSERT ON PROFORMA_ENTRIES_HEADER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PROFORMA_ENTRY_SEQ IS NULL THEN
      SELECT PROFORMA_ENTRIES_HEADER_SEQ.NEXTVAL INTO :NEW.PROFORMA_ENTRY_SEQ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."PROFORMA_ENTRIES_HEADER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFORMA_ENTRIES_HEADER
--------------------------------------------------------

  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_HEADER" ADD CONSTRAINT "PROFORMA_ENTRIES_HEADER_PK" PRIMARY KEY ("PROFORMA_ENTRY_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_HEADER" MODIFY ("PROFORMA_ENTRY_SEQ" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table PROFORMA_ENTRIES_DETAILS
--------------------------------------------------------

  CREATE TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" 
   (	"PROFORMA_ENTRY_DET_SEQ" NUMBER(*,0), 
	"PROFORMA_ENTRY_SEQ" NUMBER(*,0), 
	"FAIS_REF_NO" VARCHAR2(1 BYTE), 
	"TRAN_TYPE_SEQ" NUMBER(*,0), 
	"COST_CENTER" VARCHAR2(1 BYTE), 
	"GL_NO" NUMBER(*,0), 
	"RCA_GL" NUMBER(*,0), 
	"PREFIX" VARCHAR2(2 BYTE), 
	"SL" NUMBER(*,0), 
	"OTHER_CODE" VARCHAR2(5 BYTE), 
	"DCE" VARCHAR2(10 BYTE), 
	"PLANT_CODE" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"WO" VARCHAR2(50 BYTE), 
	"REF_BILL_NO" VARCHAR2(50 BYTE), 
	"SOURCE" VARCHAR2(50 BYTE), 
	"NATURE" VARCHAR2(50 BYTE), 
	"A_YYYY" VARCHAR2(1 BYTE), 
	"FG" VARCHAR2(1 BYTE), 
	"DEBIT" VARCHAR2(1 BYTE), 
	"CREDIT" VARCHAR2(1 BYTE), 
	"TRAN_DATE" VARCHAR2(1 BYTE), 
	"YM_POSTED" VARCHAR2(1 BYTE), 
	"SORT" NUMBER(9,0), 
	"UDF1" VARCHAR2(50 BYTE), 
	"UDF2" VARCHAR2(50 BYTE), 
	"DATE_CREATED" DATE DEFAULT systimestamp, 
	"DATE_MODIFIED" DATE DEFAULT systimestamp, 
	"DATE_REMOVED" DATE, 
	"USER_CREATED" NUMBER(*,0), 
	"USER_MODIFIED" NUMBER(*,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007362
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAIS"."SYS_C007362" ON "FAIS"."PROFORMA_ENTRIES_DETAILS" ("PROFORMA_ENTRY_DET_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger PROFORMA_ENTRIES_DETAILS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FAIS"."PROFORMA_ENTRIES_DETAILS_TRG" 
BEFORE INSERT ON PROFORMA_ENTRIES_DETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PROFORMA_ENTRY_DET_SEQ IS NULL THEN
      SELECT PROFORMA_ENTRIES_DETAILS_SEQ.NEXTVAL INTO :NEW.PROFORMA_ENTRY_DET_SEQ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FAIS"."PROFORMA_ENTRIES_DETAILS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFORMA_ENTRIES_DETAILS
--------------------------------------------------------

  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" MODIFY ("PROFORMA_ENTRY_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" MODIFY ("PROFORMA_ENTRY_DET_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" MODIFY ("FAIS_REF_NO" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" MODIFY ("TRAN_TYPE_SEQ" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" MODIFY ("RCA_GL" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" MODIFY ("USER_CREATED" NOT NULL ENABLE);
  ALTER TABLE "FAIS"."PROFORMA_ENTRIES_DETAILS" ADD PRIMARY KEY ("PROFORMA_ENTRY_DET_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;